apiVersion: v1
kind: Secret
metadata:
  name: cluster-kubeconfig
  namespace: secrets
  labels:
    app.kubernetes.io/name: cluster-kubeconfig
    app.kubernetes.io/managed-by: argocd
    purpose: cluster-access
  annotations:
    # Don't prune this resource if it's modified externally (job manages the data)
    argocd.argoproj.io/sync-options: Prune=false
type: Opaque
data:
  # This will be populated by the generate-kubeconfig job
  # ArgoCD won't try to reset this due to annotations above
  kubeconfig: ""

