apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role-argocd.yaml
  - rolebinding-argocd.yaml
  - role-secrets.yaml
  - rolebinding-secrets.yaml
  - clusterrolebinding-admin.yaml
  - cluster-kubeconfig-secret.yaml
  - cluster-kubeconfig-configmap.yaml
  - generate-kubeconfig-job.yaml
