apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-cluster-access/namespace.yaml
  - home-cluster-access/cluster-kubeconfig-secret.yaml
  - home-cluster-access/cluster-kubeconfig-configmap.yaml

