apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-autx-config
  namespace: home-autx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-configs
  volumeMode: Filesystem
