apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-http-config
  namespace: home-autx
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/managed-by: argocd
data:
  http-config.yaml: |
    # Reverse proxy configuration
    use_x_forwarded_for: true
    trusted_proxies:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16

